#!/usr/bin/env python3
"""Sync the web app's generated files from this repo.

The app lives in a different repository, because the corpus is paid course
content and this one is public. That split is exactly the condition that let the
published artifact page drift away from the repo twice, losing a whole retrieval
block once and shipping a stale guard version another time. So nothing in the
app's lib/ or data/ is hand written: it is generated here, from the files the
test suites actually check, and the generated files carry a header saying so.

    python3 tools/build_web.py /home/user/webinar-webpage/student-bot

Checks, in the same spirit as build_artifact.py:
  - the generated guards agree with tools/guards.cjs on every guard case
  - the generated retrieval module parses and indexes the corpus
  - node is available to run both
"""
import json, re, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = ("/* GENERATED by student-bot/tools/build_web.py in the\n"
          "   trader-foundation-website repo. Do not edit here: edit the source\n"
          "   file named below, then re-run the build. Hand edits are the reason\n"
          "   the published page drifted from the repo twice.\n"
          "   Source: %s */\n\n")

# The same cases build_artifact.py uses, so all three copies of the guard logic
# are pinned to one answer.
def guard_cases():
    """Read the cases out of build_artifact.py rather than keeping a third copy.
    A second list would only drift from the first, which is the failure this
    whole script exists to prevent."""
    src = (ROOT / "tools/build_artifact.py").read_text()
    body = re.search(r"^GUARD_CASES = \[(.*?)^\]", src, re.S | re.M).group(1)
    return [(None if m.group(1) == "None" else m.group(1).strip("\"'"), m.group(2))
            for m in re.finditer(r"\(\s*(None|\"[^\"]*\"|'[^']*')\s*,\s*\"([^\"]*)\"\s*\)", body)]


GUARD_CASES = None  # filled in main(), once ROOT is known to exist


def pretty(title):
    """Turn a source filename into something a student can go and find.
    Mirrors pretty() in tools/ask.py."""
    t = re.sub(r"^(module-\d+-|module-)", "", str(title or ""))
    t = re.sub(r"[-_]?(UNNUMBERED|SLIDES)$", "", t)
    t = re.sub(r"[-_]?UNNUMBERED$", "", t)
    t = re.sub(r"\.(txt|md)$", "", t)
    return t.replace("-", " ").replace("_", " ").strip().title()


def slim_corpus():
    chunks = json.loads((ROOT / "corpus/chunks.json").read_text())
    return [{
        "t": c["text"], "c": c["course"], "m": c["module"],
        "n": pretty(c["module_title"]), "p": c["part"],
        "d": c.get("recording_date") or "", "ts": c.get("timestamp") or "",
        "e": bool(c.get("timestamp_estimated")), "g": c["tag"],
    } for c in chunks]


def gen_retrieval():
    """tools/artifact-retrieval.js reads a page global named CHUNKS. Give it a
    module level one plus a setter, and export what the route needs. The body is
    copied byte for byte so the parity suite still governs it."""
    src = (ROOT / "tools/artifact-retrieval.js").read_text()
    return (BANNER % "tools/artifact-retrieval.js"
            + "let CHUNKS = [];\n"
            + src
            + "\nexport function loadCorpus(chunks){ CHUNKS = chunks; index(); }\n"
            + "export { search, cite, toks, stem, expand };\n")


def gen_scrub():
    """tools/scrub.cjs is CommonJS for tools/test_scrub.cjs. Same treatment as
    the guards: swap the export tail, change nothing above it."""
    src = (ROOT / "tools/scrub.cjs").read_text()
    src = re.sub(r"\nif \(typeof module !== \"module\"\) \{.*?\}\n", "\n", src, flags=re.S)
    src = re.sub(r"\nif \(typeof module !== \"undefined\"\) \{.*?\}\n", "\n", src, flags=re.S)
    return (BANNER % "tools/scrub.cjs"
            + src
            + "\nexport { scrubOutcomeFigures };\n")


def gen_guards():
    """tools/guards.cjs is CommonJS for the node test suites. Swap the export
    tail for an ESM one and change nothing above it."""
    src = (ROOT / "tools/guards.cjs").read_text()
    src = re.sub(r"\nif \(typeof module !== 'undefined'\) \{.*?\}\n", "\n", src, flags=re.S)
    return (BANNER % "tools/guards.cjs"
            + src
            + "\nexport { GUARDS, TICKER, guardFor, INTENT_TO_GUARD, mergeGuards };\n")


def check_guard_parity(app):
    """Run the same cases through the generated ESM guards and the repo's CJS
    guards and require identical verdicts."""
    harness = """
import { guardFor } from %s;
const cases = %s;
const out = cases.map(([, q]) => { const g = guardFor(q); return g ? g.id : null; });
console.log(JSON.stringify(out));
"""
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        (d / "package.json").write_text('{"type":"module"}')
        (d / "run.mjs").write_text(harness % (
            json.dumps(str(app / "lib/guards.js")), json.dumps(GUARD_CASES)))
        got = subprocess.run([node(), str(d / "run.mjs")], capture_output=True, text=True)
        if got.returncode:
            die("the generated guards module does not run\n" + got.stderr)
        got = json.loads(got.stdout)

        (d / "ref.cjs").write_text(
            "const {guardFor} = require(%s);\n"
            "const cases = %s;\n"
            "console.log(JSON.stringify(cases.map(([, q]) => { const g = guardFor(q); "
            "return g ? g.id : null; })));\n"
            % (json.dumps(str(ROOT / "tools/guards.cjs")), json.dumps(GUARD_CASES)))
        want = subprocess.run([node(), str(d / "ref.cjs")], capture_output=True, text=True)
        if want.returncode:
            die("tools/guards.cjs does not run\n" + want.stderr)
        want = json.loads(want.stdout)

    bad = [(c[1], w, g) for c, w, g in zip(GUARD_CASES, want, got) if w != g]
    for q, w, g in bad:
        print("  MISMATCH  %-46s repo=%s app=%s" % (q[:46], w, g))
    expected = [c[0] for c in GUARD_CASES]
    drift = [(c[1], e, w) for c, e, w in zip(GUARD_CASES, expected, want) if e != w]
    for q, e, w in drift:
        print("  DRIFT     %-46s want=%s got=%s" % (q[:46], e, w))
    return not bad and not drift


def check_scrub(app):
    """The generated scrub must agree with the one tools/test_scrub.cjs pins.
    This is compliance code and it has produced a half-redaction twice, so a
    copy of it running somewhere untested is not acceptable."""
    cases = ["Typical returns are 150 to 300 percent.",
             "A 90 over 60 win rate is what to expect.",
             "Expect gains of $2k-$5k per month.",
             "The method targets a 70 percent win rate.",
             "The 20 SMA is the line most traders watch."]
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        (d / "package.json").write_text('{"type":"module"}')
        (d / "run.mjs").write_text(
            "import { scrubOutcomeFigures } from %s;\n"
            "console.log(JSON.stringify(%s.map(s => scrubOutcomeFigures(s).text)));\n"
            % (json.dumps(str(app / "lib/scrub.js")), json.dumps(cases)))
        got = subprocess.run([node(), str(d / "run.mjs")], capture_output=True, text=True)
        if got.returncode:
            die("the generated scrub module does not run\n" + got.stderr)
        (d / "ref.cjs").write_text(
            "const { scrubOutcomeFigures } = require(%s);\n"
            "console.log(JSON.stringify(%s.map(s => scrubOutcomeFigures(s).text)));\n"
            % (json.dumps(str(ROOT / "tools/scrub.cjs")), json.dumps(cases)))
        want = subprocess.run([node(), str(d / "ref.cjs")], capture_output=True, text=True)
        if want.returncode:
            die("tools/scrub.cjs does not run\n" + want.stderr)
    if json.loads(got.stdout) != json.loads(want.stdout):
        die("the app's scrub disagrees with tools/scrub.cjs")
    print("ok    the outcome-figure scrub agrees with the repo (%d cases)" % len(cases))
    return True


def check_retrieval(app, n):
    """Index the real corpus through the generated module and require that a
    known question still reaches the module that teaches it."""
    harness = """
import { loadCorpus, search, cite } from %s;
import { readFileSync } from 'node:fs';
const chunks = JSON.parse(readFileSync(%s, 'utf8'));
loadCorpus(chunks);
const hits = search('what does volume tell you', 8, []);
console.log(JSON.stringify({n: chunks.length, top: hits.length ? cite(hits[0].chunk) : null}));
"""
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        (d / "package.json").write_text('{"type":"module"}')
        (d / "run.mjs").write_text(harness % (
            json.dumps(str(app / "lib/retrieval.js")), json.dumps(str(app / "data/chunks.json"))))
        r = subprocess.run([node(), str(d / "run.mjs")], capture_output=True, text=True)
    if r.returncode:
        die("the generated retrieval module does not run\n" + r.stderr)
    out = json.loads(r.stdout)
    if out["n"] != n:
        die("the app's corpus has %d chunks, this repo has %d" % (out["n"], n))
    if not out["top"]:
        die("retrieval returned nothing for a question the corpus answers")
    print("ok    retrieval indexes %s chunks; 'what does volume tell you' -> %s"
          % (f"{n:,}", out["top"]))
    return True


_node = None
def node():
    global _node
    if _node is None:
        for cand in ("node", "nodejs"):
            if subprocess.run(["which", cand], capture_output=True).returncode == 0:
                _node = cand
                break
        else:
            die("node is not on PATH, so the generated modules cannot be checked")
    return _node


def die(msg):
    print("\nFAILED: " + msg)
    sys.exit(1)


def main():
    global GUARD_CASES
    GUARD_CASES = guard_cases()
    if len(sys.argv) < 2:
        die("usage: build_web.py <path to the app directory>")
    app = Path(sys.argv[1]).resolve()
    if not (app / "package.json").exists():
        die("%s does not look like the app directory" % app)

    (app / "lib").mkdir(exist_ok=True)
    (app / "data").mkdir(exist_ok=True)

    (app / "lib/retrieval.js").write_text(gen_retrieval())
    (app / "lib/guards.js").write_text(gen_guards())
    (app / "lib/scrub.js").write_text(gen_scrub())

    corpus = slim_corpus()
    (app / "data/chunks.json").write_text(json.dumps(corpus, separators=(",", ":")))

    # As a JS module rather than a .md file, so it is bundled into the function
    # instead of read off a filesystem that may or may not carry it. Same reason
    # the corpus is imported rather than read: a deployment that silently loses
    # its data is worse than one that fails to build.
    prompt = (ROOT / "prompts/system.md").read_text()
    (app / "data/system.js").write_text(
        BANNER % "prompts/system.md"
        + "export const SYSTEM = " + json.dumps(prompt) + ";\n")

    print("chunks   %s  ->  data/chunks.json (%.2f MB)"
          % (f"{len(corpus):,}", (app / "data/chunks.json").stat().st_size / 1048576))
    print("prompt   %s bytes, complete (no cap on this platform)"
          % f"{len(prompt.encode()):,}")
    print()

    ok = check_guard_parity(app)
    print("%s  guards agree with the repo (%d cases)"
          % ("ok   " if ok else "FAIL ", len(GUARD_CASES)))
    if not ok:
        die("the app's guards disagree with tools/guards.cjs")
    check_retrieval(app, len(corpus))
    check_scrub(app)
    print("\nAll checks pass.")


if __name__ == "__main__":
    main()
